### ISSUE TITLE
remove `setup_requires` from `setup.py`, or add missing dependencies

### ISSUE THREAD

**Issue by gregcaporaso** [nbokulich/q2-sample-classifier#13]
`install_requires` seems to be missing some dependencies (e.g., `qiime2`, but I'm not what others, if any). You can just remove `install_requires` all together though I think, as this is intended to be a QIIME 2 plugin only, not a stand-alone package, so will have its dependencies installed through conda. It might make sense to wait until you're ready to release this though to remove `install_requires`.

**Comment by nbokulich** [comment]
One dependency not included in qiime2 is `fastcluster`... I have updated `install_requires` but expect we can remove when this is upgraded to a core qime2 plugin.

**Comment by nbokulich** [comment]
I think all missing dependencies are in there now (just tested with a fresh qiime2 conda env), so I will close this issue for now (until we need to address any related issues when converting to a qiime2 core plugin)
