### ISSUE TITLE
`detect_outliers` suggestions

### ISSUE THREAD

**Issue by gregcaporaso** [nbokulich/q2-sample-classifier#14]
> Inputs support two different modes

Could `detect_outliers` be split into a couple of different methods, tailored for different the different modes? All of the work could happen in a single function under the hood, but if mode-specific options need to be added in the future this could get confusing for users. Even if you don't want to make this change, you should catch the case where the user provided only one of `subset_category` or `subset_value` and raise an error (this will catch users otherwise). 

> possibly filtered to remove samples

It might save users some trouble if this filtering could be part of the method. Or, could the filtering be integrated into this method so users don't have to do this themselves. You could import [`filter_samples` from `q2-feature-classifier`](https://github.com/qiime2/q2-feature-table/blob/master/q2_feature_table/_filter.py#L63) to support that. 

> This series may be added to a metadata map

It could actually just be used as metadata directly now. See the (really) [new metadata tutorial](https://docs.qiime2.org/2017.6/tutorials/metadata/#metadata-from-a-qiime-2-artifact). Also, we're trying to drop the "mapping/map" nomenclature, since it's so generic. Could you refer to it as "sample metadata" or a "sample metadata file"? 

Your big doc string should ultimately be made a tutorial, as users won't find it as a doc string. I also think you should shorten the `description` for this in `plugin_setup.py`, in favor of a tutorial. This probably won't render nicely in different interfaces, and it's really intended to be more a description rather than usage documentation. You could move this info exclusively to the README for the moment. 

>  inliers have value 1, outliers have value -1

Looks like this is outdated?

**Comment by nbokulich** [comment]
👍 most suggestions have been changed in the  [tutorial] (https://github.com/nbokulich/q2-sample-classifier#outlier-detection). The large description/docstring have been shortened substantially.

> Could detect_outliers be split into a couple of different methods

I prefer keeping together for now — the two different modes really are the closely related. I prefer your other suggestion, to raise an error if only one of `subset_category` or `subset_value` are defined. This is now done [here](https://github.com/nbokulich/q2-sample-classifier/blob/master/q2_sample_classifier/classify.py#L171)

> It might save users some trouble if this filtering could be part of the method

I am always a fan of condensing methods, but this is really so dataset specific that I think it should be up to users. The purpose of filtering is described further in that paragraph (see the [tutorial] (https://github.com/nbokulich/q2-sample-classifier#outlier-detection)) — so really does depend on the sample types, and supporting basic filtering might not cut it.
