### ISSUE TITLE
visualizers should take `qiime2.MetadataCategory` as input...

### ISSUE THREAD

**Issue by gregcaporaso** [nbokulich/q2-sample-classifier#32]
rather than `qiime2.Metadata` and a string for the category. See an example [here](https://github.com/qiime2/q2-diversity/blob/ebac81a91e72c52c0a80233e51c4f554cb166ee9/q2_diversity/plugin_setup.py#L288).

This is only relevant in visualizers where a single category is used, so for example `classify-samples`, but not `predict-coordinates`.

**Comment by nbokulich** [comment]
fyi, this will not work for `maturity-index`, as the action currently uses multiple metadata categories to split the dataset prior to using `category` as the target variable.
