### ISSUE TITLE
Reduce code replication

### ISSUE THREAD

**Issue by BenKaehler** [nbokulich/q2-sample-classifier#8]
A bunch of functions are almost identical, differing only by the `scikit-learn` pipeline that they provide access to. We could perhaps replace all of them with a factory function, similar to what was done in `q2-feature-classifier`.

**Comment by gregcaporaso** [comment]
You could definitely write a function that looks something this that could be called from all of your visualizers. This would help a little bit. 

```python
def _some_name(output_dir, table, estimator,
                         metadata, category,
                         test_size, step,
                         cv, random_state, n_jobs,
                         n_estimators, stratify,
                         optimize_feature_selection,
                         parameter_tuning):

    estimator, cm, accuracy, importances = split_optimize_classify(
        table, metadata, category, estimator, output_dir,
        test_size=test_size, step=step, cv=cv, random_state=random_state,
        n_jobs=n_jobs, optimize_feature_selection=optimize_feature_selection,
        parameter_tuning=parameter_tuning, param_dist=param_dist,
        calc_feature_importance=True, scoring=mean_squared_error,
        stratify=stratify, classification=False)

    _visualize(output_dir, estimator, cm, accuracy, importances,
               optimize_feature_selection)
```

It might also be nice to define all of the default parameter settings in a dict somewhere, since those are repeated in each function definition, which creates the perfect context for getting out-dated. 

There might not be a ton more to do after these two things. Do you have other ideas @BenKaehler?

**Comment by nbokulich** [comment]
Classification and regression functions have now been compressed into two functions: `classify_samples` and `regress_samples`. These could even be collapsed into one if necessary, but separating classifiers and regressors seems logical.

>It might also be nice to define all of the default parameter settings in a dict somewhere, since those are repeated in each function definition, which creates the perfect context for getting out-dated.

redundant parameter settings are now called from the `defaults` dict (currently [line 26](https://github.com/nbokulich/q2-sample-classifier/blob/master/q2_sample_classifier/classify.py#L26))
